vpc_name: "vpc"

# VPC range

vpcCidr: 

# Subnet range
PubSub1Cidr: 
PubSub2Cidr: 
PubSub3Cidr: 
PrivSub1Cidr: 
PrivSub2Cidr: 
PrivSub3Cidr: 

# Region

region: "us-east-2"

# Zones

zone1: us-east-2a
zone2: us-east-2b
zone3: us-east-2c

state: present

#bastion vars
bastion_ami: ami-0d1c47ab964ae2b87
MYIP: 

