apiVersion: apps/v1
kind: Deployment
metadata:
  name: vapp
  labels: 
    app: vapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vapp
  template:
    metadata:
      labels:
        app: vapp
    spec:
      containers:
      - name: vapp
        image: vprofile/vprofileapp:V1
        ports:
        - name: app-port
          containerPort: 8080
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', 'until nslookup cache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']