---
- name: Setup Ec2 stack
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import Variables
      include_vars: vars/output_vars.yml

    - name: Import Variables for stack
      include_vars: vars/stacksetup.yml 

    - name: Create ec2 key
      ec2_key:
        name: stack-key
        region: "{{ region }}"
      register: stackkey_out

    - name: Save private key 
      copy:
        content: "{{stackkey_out.key.private_key}}"
        dest: "./loginkey.pem"
        mode: 0600
      when: stackkey_out.changed 

    - name: Create security group for LB
      ec2_group:
        name: elb-sg
        description: Allow port 80 from everywhere
        region: "{{ region }}" 
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: elbsg_out

    - name: Create security group for ec2
      ec2_group:
        name: ec-sg
        description: Allow port 22 from everywhere
        region: "{{ region }}" 
        vpc_id: "{{ vpc_id }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{elbsg_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id:: "{{bastionsgid}}" 
      register: ec2_out

    - name: Update sg with itw own sgid
      ec2_group:
        name: ec-sg
        description: Allow port 22 from everywhere
        region: "{{ region }}" 
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: all
            group_id:: "{{ec2_out.group_id}}""
      register: updateecsg_out 

        

