---
- name: Secgroups rules
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import Variables
      include_vars: vars/output_vars.yml

    - name: Import Variables for stack
      include_vars: vars/stacksetup.yml 

    - name: Create security group for ec2
      ec2_group:
        name: ec-sg
        description: Allow port 22 from everywhere
        region: "{{ region }}" 
        vpc_id: "{{ vpc_id }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{elbsg_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id:: "{{bastionsgid}}" 
      register: ec2_out

    - name: Update sg with itw own sgid
      ec2_group:
        name: ec-sg
        description: Allow port 22 from everywhere
        region: "{{ region }}" 
        vpc_id: "{{ vpc_id }}"
        purge_rules: no
        rules:
          - proto: all
            group_id:: "{{ec2_out.group_id}}"
      register: updateecsg_out