- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import Variables
      include_vars: vars/vpc_setup

    - name: Create VPC
      ec2_vpc_net:
         name: "{{vpc_name}}"
         cider_block: "{{vpcCidr}}"
         region: "{{region}}"
         dna_support: yes
         dns_hostnames: yes
         tenancy: default
         state: "{{state}}"
      register: vpcout    

